name: neb
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - jupytext
  - mypy
  - pip
  - scipy
  - pydantic
  - python=3.9.7
  - rdkit
  - yaml
  - ipywidgets
  - ipympl
  - nb_conda_kernels
  - xtb-python
  - openbabel
  - pip:
    - ase
    - tqdm
    - black
    - isort
