engine_name = "qcop"
program = "terachem"
path_min_method = "NEB"

[path_min_inputs]
tol = 0.002
climb = false
en_thre = 4.444444444444444e-06
rms_grad_thre = 0.002
max_rms_grad_thre = 0.005
skip_identical_graphs = true
grad_thre = 0.001
ts_grad_thre = 0.005
ts_spring_thre = 0.005
barrier_thre = 0.1
early_stop_force_thre = 0.0
early_stop_chain_rms_thre = 0.0
early_stop_corr_thre = 10.0
early_stop_still_steps_thre = 100
negative_steps_thre = 10
max_steps = 1000
v = false
preopt_with_xtb = false

[path_min_inputs.pygsm_kwds]

[path_min_inputs.fneb_kwds]

[chain_inputs]
k = 0.1
delta_k = 0.0
do_parallel = true
use_geodesic_interpolation = true
friction_optimal_gi = true
node_freezing = true
node_rms_thre = 1.0
node_ene_thre = 1.0

[gi_inputs]
nimages = 15
friction = 0.01
nudge = 0.001

[gi_inputs.extra_kwds]

[program_kwds]
cmdline_args = []

[program_kwds.keywords]

[program_kwds.extras]

[program_kwds.files]

[program_kwds.model]
method = "ub3lyp"
basis = "3-21g"

[program_kwds.model.extras]

[optimizer_kwds]
timestep = 1.0
