engine_name = "qmmm"
program = "terachem"
path_min_method = "neb"

[qmmm_inputs]
qminds_fp = "./qmindices.dat"
prmtop_fp = "./5p9i_sphere_nobox.prmtop"
rst7_fp_react = "./react.rst7"
compute_program = "chemcloud"
debug_dump_inputs = true
debug_dump_dir = "./qmmm_debug_inputs"
charge = 0
spinmult = 1
run_type = "gradient"
min_coordinates = "cartesian"

[path_min_inputs]
climb = false
en_thre = 0.0001
rms_grad_thre = 0.02
max_rms_grad_thre = 0.05
skip_identical_graphs = true
ts_grad_thre = 0.05
ts_spring_thre = 0.02
barrier_thre = 0.1
early_stop_force_thre = 0.03
negative_steps_thre = 5
positive_steps_thre = 10
use_geodesic_tangent = false
do_elem_step_checks = false
max_steps = 2
v = true

[chain_inputs]
k = 0.1
delta_k = 0.09
do_parallel = true
use_geodesic_interpolation = true
friction_optimal_gi = true
node_freezing = true
node_rms_thre = 5.0
node_ene_thre = 5.0

[gi_inputs]
nimages = 5
friction = 0.001
nudge = 0.1
align = false

[gi_inputs.extra_kwds]

[program_kwds]
cmdline_args = []

[program_kwds.keywords]
# dispersion = "d3"
threall = 1e-14
convthre =  1e-06
maxit = 200
[program_kwds.extras]




[program_kwds.files]

[program_kwds.model]
method = "b3lyp"
basis = "6-31g**"

[program_kwds.model.extras]

[optimizer_kwds]
name = "cg"
timestep = 0.5
