engine_name = "chemcloud"
program = "crest"
chemcloud_queue = "cpu"
write_qcio = false
path_min_method = "neb"

[qmmm_inputs]

[nanoreactor_inputs]
preset = "fast-oscillating"
max_candidates = 12
terachem_method = "uhf"
terachem_basis = "3-21g"
terachem_frame_stride = 5
terachem_nstep = 1600
terachem_timestep = 0.5
terachem_tinit = 1200.0
terachem_thermostat = "langevin"
terachem_t0 = 1500.0
terachem_lnvtime = 200.0
terachem_convthre = 0.005
terachem_levelshift = true
terachem_levelshiftvala = 0.3
terachem_levelshiftvalb = 0.1
terachem_scf = "diis+a"
terachem_maxit = 300
terachem_md_r1 = 5.8
terachem_md_k1 = 3.5
terachem_md_r2 = 3.6
terachem_md_k2 = 6.0
terachem_mdbc_hydrogen = true
terachem_mdbc_mass_scaled = true
terachem_mdbc_t1 = 300
terachem_mdbc_t2 = 100

[path_min_inputs]
climb = false
en_thre = 0.0001
rms_grad_thre = 0.02
max_rms_grad_thre = 0.05
skip_identical_graphs = true
ts_grad_thre = 0.05
ts_spring_thre = 0.02
barrier_thre = 0.1
early_stop_force_thre = 0.03
negative_steps_thre = 5
positive_steps_thre = 10
use_geodesic_tangent = false
do_elem_step_checks = true
max_steps = 500
v = 0

[chain_inputs]
k = 0.1
delta_k = 0.09
do_parallel = true
use_geodesic_interpolation = true
friction_optimal_gi = true
node_freezing = true
node_rms_thre = 5.0
node_ene_thre = 5.0
frozen_atom_indices = ""

[gi_inputs]
nimages = 15
friction = 0.001
nudge = 0.01
align = true

[gi_inputs.extra_kwds]

[network_inputs]
n_max_conformers = 10
subsample_confs = true
conf_rmsd_cutoff = 0.5
network_nodes_are_conformers = false
maximum_barrier_height = 1000
use_slurm = false
verbose = true
tolerate_kinks = true
CREST_temp = 298.15
CREST_ewin = 6.0
collapse_node_rms_thre = 5.0
collapse_node_ene_thre = 5.0

[program_kwds]
cmdline_args = []

[program_kwds.keywords]
threads = 1

[program_kwds.extras]

[program_kwds.files]

[program_kwds.model]
method = "gfn2"
basis = "gfn2"

[program_kwds.model.extras]

[optimizer_kwds]
name = "cg"
